stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_production:
  stage: deploy
  tags:
    - ubuntu
  script:
    - echo "Deploy to production server"
    - npm install
    - forever start .
  environment: production
  only:
  - master